#!/usr/bin/env bash
# Nginx user
# Nginx must be on port 8080
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080 default_server/g' /etc/nginx/sites-available/default
sed -i '1 i user nginx;' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
