#!/usr/bin/env bash
#Script to install nginx on web server
apt-get update -y
apt-get install nginx -y

echo 'Holberton School for the win!' > /var/www/html/index.html

service nginx restart

update-rc.d nginx defaults
