#!/usr/bin/env bash
#Script to install nginx on web server
apt-get update -y
apt-get install nginx -y

mkdir /var/www/html
touch /var/www/html/index.html

echo 'Holberton School' > /var/www/html/index.html

service nginx restart

update-rc.d nginx defaults
