#!/usr/bin/env bash

files=(
    "0-transfer_file"
    "1-install_nginx_web_server"
    "2-setup_a_domain_name"
    "3-redirection"
    "4-not_found_page_404"
)

for file in "${files[@]}"; do
    touch "$file"
    echo "#!/usr/bin/env bash" > "$file"
    chmod +x "$file"
done

touch "5-design_a_beautiful_404_page.html"
